import '../../header-component/scripts/header-component.js';
import '../../home-component/scripts/home-component.js';
import '../../brands-component/scripts/brands-component.js';
import '../../about-me-component/scripts/about-me-component.js';
import '../../contact-me-component/scripts/contact-me-component.js';  
import '../../services-component/scripts/services-component.js';  
import '../../gallery-component/scripts/gallery-component.js';  
import '../../article-component/scripts/article-component.js';  
import '../../footer-component/scripts/footer-component.js';  